name: time_series
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.4.0=py39h06a4308_0
  - annotated-types=0.6.0=py39h06a4308_0
  - anyio=4.2.0=py39h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - arrow=1.2.3=py39h06a4308_1
  - astor=0.8.1=py39h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attrs=23.1.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backoff=2.2.1=py39h06a4308_1
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h6a678d5_7
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.16.0=py39h5eee18b_0
  - cfitsio=3.470=h5893167_7
  - chardet=3.0.4=py39h06a4308_1003
  - charls=2.2.0=h2531618_0
  - cmake=3.26.4=h96355d8_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cssselect=1.2.0=py39h06a4308_0
  - cuda-version=11.3=hbc958af_3
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.9.2.26=cuda11_0
  - cupti=11.3.1=0
  - cupy=13.3.0=py39h8710ada_2
  - cupy-core=13.3.0=py39h4601a17_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.2=py39h5eee18b_0
  - dask-core=2023.6.0=py39h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - dbus-python=1.2.18=py39hfc3c560_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docopt=0.6.2=py39h06a4308_1
  - exceptiongroup=1.2.0=py39h06a4308_0
  - expat=2.5.0=h6a678d5_0
  - fasteners=0.14.1=py_3
  - fastrlock=0.8.2=py39h3d6467e_2
  - fftw=3.3.9=h5eee18b_2
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - future=0.18.2=py39h06a4308_1
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py39h06a4308_0
  - httpcore=1.0.2=py39h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2023.1.23=py39hc4b7b5f_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=3.1.2=py39h06a4308_0
  - jmespath=1.0.1=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.33=py39h06a4308_0
  - jsonschema=4.17.3=py39h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy_loader=0.2=py39h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h7f8727e_2
  - libllvm11=11.1.0=h9e868ea_6
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - libxslt=1.1.37=h5eee18b_1
  - libzopfli=1.0.3=he6710b0_0
  - llvmlite=0.39.1=py39he621ea3_0
  - locket=1.0.0=py39h06a4308_0
  - lockfile=0.12.2=py39h06a4308_0
  - lxml=4.9.3=py39hdbbb534_0
  - lz4-c=1.9.4=h6a678d5_0
  - magma=2.7.0=h8db6258_0
  - mako=1.1.3=py_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.7.2=py39h06a4308_0
  - matplotlib-base=3.7.2=py39h1128e8f_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - more-itertools=8.10.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.0.4=py39h5eee18b_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - netifaces=0.11.0=py39h5eee18b_0
  - networkx=3.1=py39h06a4308_0
  - ninja-base=1.10.2=hd09550d_5
  - nltk=3.8.1=py39h06a4308_0
  - numba=0.56.4=py39h71a7301_1
  - numexpr=2.8.4=py39he184ba9_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.2=hb9d3cd8_0
  - ordered-set=4.1.0=py39h06a4308_0
  - packaging=23.2=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py39h06a4308_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pynacl=1.5.0=py39h5eee18b_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h955ad1f_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytoml=0.1.21=pyhd3eb1b0_0
  - pytorch-lightning=2.0.3=py39h06a4308_0
  - pytz=2022.1=py39h06a4308_0
  - pywavelets=1.4.1=py39h5eee18b_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py39h5eee18b_1
  - pyzmq=25.1.2=py39h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rhash=1.4.3=hdbd6064_0
  - scikit-image=0.20.0=py39h6a678d5_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - secretstorage=3.3.1=py39h06a4308_1
  - setuptools=68.2.2=py39h06a4308_0
  - shapely=2.0.1=py39h0fbb895_0
  - sip=6.7.12=py39h6a678d5_0
  - slicer=0.0.7=pyhd3eb1b0_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.0=py39h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py39h06a4308_0
  - sqlalchemy=2.0.25=py39h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tabulate=0.9.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tifffile=2023.4.12=py39h06a4308_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py39h06a4308_0
  - toolz=0.12.0=py39h06a4308_0
  - torchmetrics=0.11.4=py39h2f386ee_1
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.41.2=py39h06a4308_0
  - xlrd=1.2.0=py_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==1.4.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - altair==5.2.0
      - anthropic==0.49.0
      - appdirs==1.4.4
      - argcomplete==1.10.3
      - asgiref==3.8.1
      - asttokens==2.4.1
      - audioread==3.0.1
      - authlib==1.6.5
      - auto-gptq==0.7.1
      - autofaiss==2.17.0
      - autoflake==2.3.1
      - av==14.2.0
      - axial-positional-embedding==0.2.1
      - baostock==0.8.9
      - bcembedding==0.1.3
      - bcrypt==4.2.0
      - beartype==0.16.4
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.9.0
      - blis==1.0.1
      - blobfile==2.1.1
      - boto3==1.27.0
      - botocore==1.30.0
      - bravado==11.0.3
      - bravado-core==5.17.1
      - build==1.2.2.post1
      - bypy==1.8.9
      - cachetools==5.3.1
      - catalogue==2.0.10
      - charset-normalizer==2.1.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.16
      - click==8.1.7
      - click-datetime==0.2
      - cloudpathlib==0.20.0
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - colt5-attention==0.10.18
      - comm==0.2.2
      - compressed-rtf==1.0.6
      - conda-pack==0.8.0
      - confection==0.1.5
      - contourpy==1.1.0
      - convertdate==2.4.0
      - cozepy==0.20.0
      - cryptography==3.4.8
      - cx-freeze==6.15.11
      - cymem==2.0.8
      - cython==0.29.34
      - dataclasses-json==0.6.3
      - datasets==2.18.0
      - debugpy==1.8.1
      - deepsearch-glm==1.0.0
      - denoising-diffusion-pytorch==1.9.5
      - deprecated==1.2.14
      - dill==0.3.8
      - distro==1.9.0
      - distro-info==1.0
      - docker-pycreds==0.4.0
      - docling==2.12.0
      - docling-core==2.10.0
      - docling-ibm-models==3.1.0
      - docling-parse==3.0.0
      - docstring-parser==0.16
      - docx2txt==0.8
      - durationpy==0.9
      - easydict==1.7
      - easyocr==1.7.2
      - ebcdic==1.1.1
      - einops==0.7.0
      - ema-pytorch==0.3.2
      - embedding-reader==1.7.0
      - emoji==2.11.0
      - et-xmlfile==1.1.0
      - etils==1.5.2
      - eval-type-backport==0.2.2
      - executing==2.0.1
      - extract-msg==0.28.7
      - faiss-cpu==1.8.0
      - faiss-gpu==1.7.2
      - fastapi==0.110.0
      - fastjsonschema==2.19.1
      - fastshap==0.3.1
      - ffmpy==0.3.2
      - filelock==3.12.2
      - filetype==1.2.0
      - fire==0.5.0
      - flask==3.0.3
      - flask-swagger==0.2.14
      - flatbuffers==24.3.25
      - fonttools==4.31.2
      - fqdn==1.5.1
      - fsspec==2023.6.0
      - gast==0.5.4
      - gekko==1.0.7
      - gensim==4.3.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gluonts==0.14.4
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.2
      - google-api-python-client==2.165.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.65.0
      - googledrivedownloader==0.4
      - gradio==4.44.1
      - gradio-client==1.3.0
      - greenlet==3.0.3
      - gributils==0.11.0
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - h5py==3.12.1
      - hijri-converter==2.2.3
      - holidays==0.13
      - httplib2==0.20.2
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.26.5
      - humanfriendly==10.0
      - imageio==2.28.1
      - imapclient==2.1.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.3
      - ipython==8.12.3
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jieba==0.42.1
      - jiter==0.9.0
      - joblib==1.3.2
      - json-tricks==3.16.1
      - jsonlines==3.1.0
      - jsonpath-rw==1.4.0
      - jsonpointer==2.4
      - jsonref==1.1.0
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keras==3.7.0
      - keyring==23.5.0
      - korean-lunar-calendar==0.3.1
      - kubernetes==31.0.0
      - langchain==0.1.13
      - langchain-community==0.0.29
      - langchain-core==0.1.35
      - langchain-openai==0.0.2.post1
      - langchain-text-splitters==0.0.1
      - langchainhub==0.1.21
      - langcodes==3.4.1
      - langdetect==1.0.9
      - langsmith==0.1.36
      - language-data==1.2.0
      - launchpadlib==1.10.16
      - lazr-restfulclient==0.14.4
      - lazr-uri==1.0.6
      - libclang==18.1.1
      - librosa==0.11.0
      - lightgbm==4.3.0
      - lightning==2.1.3
      - lightning-utilities==0.8.0
      - lit==16.0.6
      - llamafactory==0.9.3.dev0
      - lmdb==1.3.0
      - local-attention==1.9.0
      - loguru==0.7.2
      - macaroonbakery==1.3.1
      - mamba-ssm==1.2.0.post1
      - marisa-trie==1.2.1
      - markdown==3.4.3
      - markdown-it-py==3.0.0
      - marko==2.1.2
      - marshmallow==3.20.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.4.1
      - mlcroissant==1.0.0
      - mmengine==0.8.2
      - mmh3==5.0.1
      - model-index==0.1.11
      - monotonic==1.6
      - mpire==2.10.2
      - msgpack==1.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - namex==0.0.7
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.3
      - neo4j==5.18.0
      - neptune==1.3.2
      - ninja==1.11.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.5.1
      - oauthlib==3.2.2
      - onnxruntime==1.19.2
      - openai==1.8.0
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.9
      - openmim==0.3.9
      - openpyxl==3.1.5
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-instrumentation==0.48b0
      - opentelemetry-instrumentation-asgi==0.48b0
      - opentelemetry-instrumentation-fastapi==0.48b0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - opentelemetry-util-http==0.48b0
      - opt-einsum==3.3.0
      - optree==0.11.0
      - orjson==3.10.0
      - overrides==7.7.0
      - paddle-bfloat==0.1.7
      - paddlepaddle==2.6.1
      - paddlepaddle-gpu==2.3.2
      - pandas==2.2.3
      - pandas-stubs==2.2.2.240807
      - pandocfilters==1.5.1
      - paramiko==2.9.3
      - patchelf==0.17.2.1
      - patool==1.15.0
      - pdfminer-six==20191110
      - peft==0.12.0
      - pillow==10.4.0
      - pipreqs==0.5.0
      - platformdirs==3.9.1
      - pooch==1.8.2
      - posthog==3.7.0
      - preshed==3.0.9
      - prettytable==3.8.0
      - product-key-memory==0.2.10
      - properscoring==0.1
      - proto-plus==1.26.1
      - protobuf==4.25.6
      - psutil==5.9.5
      - pure-eval==0.2.2
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyclipper==1.3.0.post6
      - pycryptodome==3.18.0
      - pycryptodomex==3.20.0
      - pycups==2.0.1
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydantic-settings==2.7.0
      - pydub==0.25.1
      - pyflakes==3.2.0
      - pygrib==2.1.6
      - pyjwt==2.3.0
      - pymacaroons==0.13.0
      - pymeeus==0.5.12
      - pymupdf==1.24.0
      - pymupdfb==1.24.0
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pyproj==3.6.1
      - pyproject-hooks==1.2.0
      - pyrfc3339==1.1
      - pyrsistent==0.19.3
      - python-bidi==0.6.3
      - python-debian==0.1.49
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-graphviz==0.21
      - python-iso639==2024.2.7
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - python-pptx==1.0.2
      - pytorch-fid==0.3.0
      - rapidfuzz==3.7.0
      - rdflib==7.1.1
      - readability-lxml==0.8.1
      - reformer-pytorch==1.4.4
      - regex==2023.12.25
      - reportlab==3.6.8
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3987==1.3.8
      - rich==13.4.2
      - rouge==1.0.1
      - rouge-chinese==1.0.3
      - rouge-score==0.1.2
      - rsa==4.9
      - rtree==1.3.0
      - ruff==0.11.0
      - s3transfer==0.6.1
      - safetensors==0.4.5
      - scikit-base==0.6.1
      - scikit-learn==1.3.2
      - scipy==1.8.0
      - semantic-version==2.10.0
      - semchunk==2.2.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shap==0.45.0
      - shellingham==1.5.4
      - shtab==1.7.1
      - similarities==1.1.7
      - simplejson==3.19.1
      - six==1.17.0
      - sktime==0.24.1
      - smart-open==7.0.5
      - smmap==5.0.0
      - some-package==0.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - speechrecognition==3.8.1
      - srsly==2.4.8
      - sse-starlette==2.1.3
      - ssh-import-id==5.11
      - stack-data==0.6.3
      - starlette==0.36.3
      - swagger-spec-validator==3.0.3
      - tenacity==8.2.3
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.5.1
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.3.0
      - text2vec==1.2.9
      - textract==1.6.5
      - tf-keras==2.18.0
      - thinc==8.3.2
      - threadpoolctl==3.2.0
      - thundersvm==0.3.12
      - tiktoken==0.5.2
      - timm==0.9.16
      - tokenizers==0.21.0
      - tomlkit==0.12.0
      - torc==0.1.1
      - torch==2.2.2
      - torch-tb-profiler==0.4.1
      - torchaudio==2.2.2+cu118
      - torchcp==0.1.2
      - torchprofile==0.0.4
      - torchvision==0.17.2
      - tornado==6.4
      - tqdm==4.66.6
      - traitlets==5.14.2
      - transformers==4.49.0
      - transformers-stream-generator==0.0.5
      - triton==2.2.0
      - trl==0.9.6
      - tslearn==0.5.2
      - typer==0.12.5
      - types-pytz==2024.2.0.20241003
      - types-requests==2.32.0.20241016
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tyro==0.8.14
      - tzdata==2023.3
      - tzlocal==5.2
      - unrar==0.4
      - unstructured==0.11.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - utils==1.0.2
      - uvicorn==0.29.0
      - uvloop==0.21.0
      - vmdpy==0.2
      - wadllib==1.3.6
      - wandb==0.16.6
      - wasabi==1.1.3
      - watchfiles==0.24.0
      - wcwidth==0.2.6
      - weasel==0.4.1
      - webcolors==1.13
      - websocket-client==1.6.1
      - websockets==14.2
      - werkzeug==3.1.3
      - wrapt==1.16.0
      - xdg==5.0.0
      - xlsxwriter==3.2.0
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.40.1
      - yarg==0.1.9
      - yarl==1.9.4
      - zipp==3.8.1
prefix: /home/ps/anaconda3/envs/time_series
